name: Generate Snake

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Generates the snake game from a Python script
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/output.svg

      # Commits the new Snake Animation to the dist folder
      - name: Commit Snake Animation
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add dist/output.svg
          git commit -m "Updated snake animation"
          git push

      # Uploads the generated Snake Animation as an artifact
      - name: Upload Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/output.svg
